//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TalentosEntities : DbContext
    {
        public TalentosEntities()
            : base("name=TalentosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conhecimento> Conhecimento { get; set; }
        public virtual DbSet<Conhecimento_Pessoa> Conhecimento_Pessoa { get; set; }
        public virtual DbSet<Horario_Pessoa> Horario_Pessoa { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<Tempo_Pessoa> Tempo_Pessoa { get; set; }
        public virtual DbSet<Trabalho_Horario> Trabalho_Horario { get; set; }
        public virtual DbSet<Trabalho_Tempo> Trabalho_Tempo { get; set; }
    }
}
