//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pessoa()
        {
            this.Conhecimento_Pessoa = new HashSet<Conhecimento_Pessoa>();
            this.Horario_Pessoa = new HashSet<Horario_Pessoa>();
            this.Tempo_Pessoa = new HashSet<Tempo_Pessoa>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string nome { get; set; }
        public string skype { get; set; }
        public string telefone { get; set; }
        public string linkedin { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string portfolio { get; set; }
        public string salario_por_hora { get; set; }
        public string experiencia_tecnologia { get; set; }
        public string link_crud { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conhecimento_Pessoa> Conhecimento_Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario_Pessoa> Horario_Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tempo_Pessoa> Tempo_Pessoa { get; set; }
    }
}
